### ISSUE TITLE
Has networkCoAuthor eliminated some attributes such as AU_CO?

### ISSUE THREAD

**Issue by sshojiro** [UWNETLAB/metaknowledge#5]
Hi,

I'm attempting to analyze the publication information on the relationship between nations and my research field's publications. It seems that metaknowledge drops the `AU_CO` as author country in WOS through `networkCoAuthor` method.
http://networkslab.org/metaknowledge/documentation/metaknowledgeFull#networkCoAuthor

Do you have any alternatives to retrieve a graph of nation-wise co-author network? If you modify the method in the future, please let me know that.

Thanks in advance!

**Comment by tcrick** [comment]
Not sure if you're still working with metaknowledge (sorry for the delay) but if you are, you mention that `AU_CO` is dropped by `networkCoAuthor` - can you direct me to where you see this tag before it's dropped? I can't find it in metaknowledge or in any records collected from Web of Science.

In general, I think an author country tag would be difficult, because you need to determine which to choose if there are more than one country. Web of Science does have a `C1` / `authAddress` field that has the full addresses of the authors, which you might be able to parse yourself to get the countries. This field is fairly inconsistent and unreliable in terms of mapping to authors, but perhaps this doesn't matter for your purposes!

**Comment by sshojiro** [comment]
@tcrick Thanks for the comment; I lost the code that met AU_CO... Yeah, it seemed that the country(-ies) of authors are difficult to identify. I'll play more around the bibliometrics, honestly I'm new to the field of research. Thank you again for your taking care!

**Comment by sshojiro** [comment]
I might created AU_CO field via the `bibliometrics` package in R.
